#!/usr/bin/env python3
"""Generate the character color palette table shared by the web hosts.

PIN stores body colors (skin, eye, lip, hair, facial hair) in
``characters.json`` (``Visuals.SkinColor`` etc.) as packed light-dark RGB565
pairs. Those values come from ``dbvisualrecords::WarpaintPalette`` rows
identified by the palette id the client sends in the creation form
(``SkinColorId``, ``EyeColorId``, ``HairColorId``). Without resolving the
palette, every created character kept the hardcoded default template colors
for every slot regardless of what the player picked — which is exactly the
"same skin/face for every character" bug.

The web hosts cannot read clientdb.sd2 at runtime, so this tool precomputes
every WarpaintPalette's combined color1 (highlight/shadow) value using the
exact same FColor.CombineLightDark formula the GameServer uses, and writes a
Dictionary<uint, uint> the creation code can look up.
"""

import argparse
import os
import sys
import tempfile
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sdb_dump import (  # noqa: E402
    KNOWN_TABLES,
    StaticDB,
    apply_column_names,
    ffnv32,
    harvest_pin_names,
    load_names,
)

TOOLS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO_ROOT = os.path.dirname(TOOLS_DIR)
GAME_SERVER_DIR = os.path.join(REPO_ROOT, "UdpHosts", "GameServer")
DEFAULT_OUT = os.path.join(REPO_ROOT, "Lib", "Shared.Common", "Characters",
                           "CharacterColorPalettes.cs")

HEADER = '''//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by Tools/SdbDump/character_colors.py from clientdb.sd2 (patch __PATCH__).
//     Do not edit by hand; re-run the generator when the SDB changes:
//         python3 Tools/SdbDump/character_colors.py
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Shared.Common.Characters;

/// <summary>
/// Packed light-dark body color for every <c>dbvisualrecords::WarpaintPalette</c>
/// the client can pick from on the character creation form (build __PATCH__).
///
/// The palette's color1 highlight+shadow are combined through the same
/// <c>FColor.CombineLightDark</c> formula the GameServer uses (low 16 bits =
/// shadow RGB565, high 16 bits = highlight RGB565) so the value stored in
/// <c>CharacterVisualsRecord.SkinColor</c> / <c>EyeColor</c> / <c>LipColor</c> /
/// <c>HairColor</c> / <c>FacialHairColor</c> matches the color the player
/// actually picked, instead of every character silently inheriting the admin
/// template's default skin/hair/eye.
/// </summary>
public static class CharacterColorPalettes
{
    /// <summary>
    /// Resolve a palette id to its packed ARGB color (light-dark RGB565 pair).
    /// Returns false when the id is 0 or unknown, leaving the field at its
    /// prior value (the character keeps whatever was stored before).
    /// </summary>
    public static bool TryGet(uint paletteId, out uint packedColor)
    {
        return ByPaletteId.TryGetValue(paletteId, out packedColor);
    }

    private static readonly Dictionary<uint, uint> ByPaletteId = new()
    {
'''

FOOTER = '''    };
}
'''


def argb8888_to_rgb565(argb):
    argb &= 0xFFFFFFFF
    r = ((argb >> 16) & 0xFF) >> 3
    g = ((argb >> 8) & 0xFF) >> 2
    b = (argb & 0xFF) >> 3
    return (r & 0x1F) << 11 | (g & 0x3F) << 5 | (b & 0x1F)


def combine_light_dark(light, dark):
    return (argb8888_to_rgb565(dark) & 0xFFFF) | ((argb8888_to_rgb565(light) & 0xFFFF) << 16)


def find_sdb(explicit):
    if explicit:
        if not os.path.isfile(explicit):
            sys.exit(f"error: no SDB file at {explicit}")
        return explicit

    direct = os.path.join(TOOLS_DIR, "clientdb.sd2")
    if os.path.isfile(direct):
        return direct

    parts = [os.path.join(TOOLS_DIR, "clientdb.zip.001"),
             os.path.join(TOOLS_DIR, "clientdb.zip.002")]
    if not all(os.path.isfile(p) for p in parts):
        sys.exit("error: pass --sdb PATH to clientdb.sd2")

    extracted = os.path.join(tempfile.gettempdir(), "pin_charcolors_clientdb.sd2")
    assembled = os.path.join(tempfile.gettempdir(), "pin_charcolors_clientdb.zip")
    with open(assembled, "wb") as out:
        for part in parts:
            with open(part, "rb") as fh:
                out.write(fh.read())
    with zipfile.ZipFile(assembled) as z:
        members = [n for n in z.namelist() if n.endswith(".sd2")]
        if not members:
            sys.exit(f"error: no .sd2 member in {parts}")
        with z.open(members[0]) as src, open(extracted, "wb") as dst:
            dst.write(src.read())
    return extracted


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--sdb", help="path to clientdb.sd2")
    parser.add_argument("--out", default=DEFAULT_OUT, help="where to write the generated C# file")
    args = parser.parse_args(argv)

    db = StaticDB(find_sdb(args.sdb))

    table_names, col_by_hash = harvest_pin_names(GAME_SERVER_DIR)
    known = KNOWN_TABLES + [n for n in table_names if n not in KNOWN_TABLES]
    by_id = {ffnv32(n): n for n in known}
    for t in db.tables:
        if t["id"] in by_id:
            t["name"] = by_id[t["id"]]
    apply_column_names(db, col_by_hash)
    db.resolve_names(load_names(None))

    palettes_table = db.find_table("dbvisualrecords::WarpaintPalette")
    if palettes_table is None:
        sys.exit("error: dbvisualrecords::WarpaintPalette not found")

    entries = {}
    for row in db.rows(palettes_table):
        pid = row.get("id")
        if pid is None or pid == 0:
            continue
        packed = combine_light_dark(row["color1_highlight"], row["color1_shadow"])
        entries[pid] = packed

    lines = [HEADER.rstrip("\n").replace("__PATCH__", db.patch)]
    for pid in sorted(entries):
        lines.append(f"        [{pid}u] = 0x{entries[pid]:08x}u,")
    lines.append(FOOTER.lstrip("\n"))

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write("\n".join(lines))

    print(f"wrote {args.out} ({len(entries)} palettes, SDB patch {db.patch})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
