#!/usr/bin/env python3
"""Generate the battleframe default warpaint table shared by the web hosts.

PIN stores the armor colors of a character in ``characters.json``
(``Visuals.Warpaint``) and both surfaces that render the character — the web
character list (selection screen) and the GameServer over gRPC — are fed from
that one record. The client falls back to its built-in default avatar (the
purple Raptor, i.e. the admin account's hardcoded look) whenever a record
carries no colors, so a created character must not leave its warpaint empty:
``CharacterCreation.Create`` stamps the chosen chassis' own stock colors onto
it instead.

Those stock colors come from the static database, which the web hosts cannot
read at runtime. This tool therefore precomputes them, exactly like
``GameServer/StaticDB/SDBUtils.cs::GetChassisWarpaint(chassisId, 0, 0, 0, 0)``:

    dbitems::Battleframe.default_{fullbody,armor,bodysuit,glow}_palette_id
        -> dbvisualrecords::WarpaintPalette (type_flags, color1-7 highlight/shadow)

combined into the 7 packed light-dark colors the record carries (low 16 bits
= shadow RGB565, high 16 bits = highlight RGB565), with fullbody, armor,
bodysuit and glow applied in that order (later palettes override earlier
slots).

Usage:
    python3 chassis_warpaints.py [--sdb PATH] [--out PATH]

``--sdb`` defaults to ``Tools/clientdb.sd2`` when it exists, otherwise the
split archive ``Tools/clientdb.zip.001``/``.002`` is assembled in a temp
directory. ``--out`` defaults to
``Lib/Shared.Common/Characters/ChassisDefaultWarpaints.cs``.

Run it whenever the shipped ``clientdb.sd2`` changes; the generated file
carries the SDB patch string it was built from, so a stale table is visible.
"""

import argparse
import os
import sys
import tempfile
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sdb_dump import (  # noqa: E402
    KNOWN_TABLES,
    StaticDB,
    apply_column_names,
    ffnv32,
    harvest_pin_names,
    load_names,
)

TOOLS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO_ROOT = os.path.dirname(TOOLS_DIR)
GAME_SERVER_DIR = os.path.join(REPO_ROOT, "UdpHosts", "GameServer")
DEFAULT_OUT = os.path.join(REPO_ROOT, "Lib", "Shared.Common", "Characters",
                           "ChassisDefaultWarpaints.cs")

# The baseline SDBUtils.GetChassisWarpaint starts from: colors = 7 x 4278190080
BASELINE = [4278190080] * 7

HEADER = '''//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by Tools/SdbDump/chassis_warpaints.py from clientdb.sd2 (patch __PATCH__).
//     Do not edit by hand; re-run the generator when the SDB changes:
//         python3 Tools/SdbDump/chassis_warpaints.py
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Shared.Common.Characters;

/// <summary>
/// The 7 packed light-dark armor colors each battleframe chassis ships with in
/// the static database (build __PATCH__): dbitems::Battleframe default palette ids
/// resolved through dbvisualrecords::WarpaintPalette, combined exactly the way
/// the GameServer's SDBUtils.GetChassisWarpaint(chassisId, 0, 0, 0, 0) combines
/// them (fullbody, then armor, then bodysuit, then glow override the slots).
///
/// A created character is stamped with its chosen chassis' stock colors at
/// creation time (CharacterCreation.Create) so the character wears its frame's
/// own armor. Without this the record's warpaint would stay empty and the
/// client would fall back to its built-in default avatar — the purple Raptor
/// that is the admin account's hardcoded look — making every new character
/// appear to duplicate the admin's armor color.
///
/// Chassis the table does not know (no resolvable default palette in the SDB)
/// are absent on purpose: for those the GameServer already wears the chassis'
/// default SDB warpaint in game, and an empty record warpaint keeps that path.
/// </summary>
public static class ChassisDefaultWarpaints
{
    /// <summary>
    /// The stock 7 colors per chassis (packed light-dark RGB565 pairs), indexed
    /// by the chassis SDB id, or null when the chassis carries no resolvable
    /// default palette.
    /// </summary>
    public static IReadOnlyDictionary<uint, uint[]> ByChassis { get; } = new Dictionary<uint, uint[]>
    {
'''

FOOTER = '''    };

    /// <summary>The chassis' stock colors, or false when it carries none.</summary>
    public static bool TryGet(uint chassisId, out uint[] colors)
    {
        if (ByChassis.TryGetValue(chassisId, out colors))
        {
            return true;
        }

        colors = [];
        return false;
    }
}
'''


def argb8888_to_rgb565(argb):
    """SDBUtils.ARGB8888ToRGB565."""
    argb &= 0xFFFFFFFF
    r = ((argb >> 16) & 0xFF) >> 3
    g = ((argb >> 8) & 0xFF) >> 2
    b = (argb & 0xFF) >> 3
    return (r & 0x1F) << 11 | (g & 0x3F) << 5 | (b & 0x1F)


def combine_light_dark(light, dark):
    """SDBUtils.FColor.CombineLightDark(light, dark)."""
    return (argb8888_to_rgb565(dark) & 0xFFFF) | ((argb8888_to_rgb565(light) & 0xFFFF) << 16)


def chassis_default_warpaint(frame, palettes):
    """Replica of SDBUtils.GetChassisWarpaint(chassisId, 0, 0, 0, 0).Colors."""
    inputs = [
        palettes.get(frame["default_fullbody_palette_id"]),
        palettes.get(frame["default_armor_palette_id"]),
        palettes.get(frame["default_bodysuit_palette_id"]),
        palettes.get(frame["default_glow_palette_id"]),
    ]
    colors = list(BASELINE)
    for data in inputs:
        if data is None:
            continue
        palette_colors = [
            combine_light_dark(data[f"color{i}_highlight"], data[f"color{i}_shadow"])
            for i in range(1, 8)
        ]
        if data["type_flags"] & (1 << 4):  # fullbody
            colors[:] = palette_colors
        if data["type_flags"] & (1 << 0):  # armor
            colors[0:3] = palette_colors[0:3]
        if data["type_flags"] & (1 << 1):  # bodysuit
            colors[3:5] = palette_colors[3:5]
        if data["type_flags"] & (1 << 3):  # glow
            colors[5:7] = palette_colors[5:7]
    return colors


def find_sdb(explicit):
    if explicit:
        if not os.path.isfile(explicit):
            sys.exit(f"error: no SDB file at {explicit}")
        return explicit

    direct = os.path.join(TOOLS_DIR, "clientdb.sd2")
    if os.path.isfile(direct):
        return direct

    parts = [os.path.join(TOOLS_DIR, "clientdb.zip.001"),
             os.path.join(TOOLS_DIR, "clientdb.zip.002")]
    if not all(os.path.isfile(p) for p in parts):
        sys.exit("error: pass --sdb PATH to clientdb.sd2 (the split "
                 "Tools/clientdb.zip.001/.002 archive was not found)")

    # The assembly must outlive this function, so it goes to the system temp
    # dir (fixed name, overwritten on each run) rather than a context-managed
    # temp directory.
    extracted = os.path.join(tempfile.gettempdir(), "pin_chassis_warpaints_clientdb.sd2")
    assembled = os.path.join(tempfile.gettempdir(), "pin_chassis_warpaints_clientdb.zip")
    with open(assembled, "wb") as out:
        for part in parts:
            with open(part, "rb") as fh:
                out.write(fh.read())
    with zipfile.ZipFile(assembled) as z:
        members = [n for n in z.namelist() if n.endswith(".sd2")]
        if not members:
            sys.exit(f"error: no .sd2 member in {parts}")
        with z.open(members[0]) as src, open(extracted, "wb") as dst:
            dst.write(src.read())
    return extracted


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--sdb", help="path to clientdb.sd2 (default: Tools/)")
    parser.add_argument("--out", default=DEFAULT_OUT,
                        help="where to write the generated C# file")
    args = parser.parse_args(argv)

    db = StaticDB(find_sdb(args.sdb))

    # Same name labelling the dumper uses.
    table_names, col_by_hash = harvest_pin_names(GAME_SERVER_DIR)
    known = KNOWN_TABLES + [n for n in table_names if n not in KNOWN_TABLES]
    by_id = {ffnv32(n): n for n in known}
    for t in db.tables:
        if t["id"] in by_id:
            t["name"] = by_id[t["id"]]
    apply_column_names(db, col_by_hash)
    db.resolve_names(load_names(None))

    frames_table = db.find_table("dbitems::Battleframe")
    palettes_table = db.find_table("dbvisualrecords::WarpaintPalette")
    if frames_table is None or palettes_table is None:
        sys.exit("error: dbitems::Battleframe / dbvisualrecords::WarpaintPalette "
                 "not found in the SDB")

    palettes = {row["id"]: row for row in db.rows(palettes_table) if row["id"] is not None}
    entries = {}
    for row in db.rows(frames_table):
        if row["id"] is None:
            continue
        colors = chassis_default_warpaint(row, palettes)
        if colors != BASELINE:
            entries[row["id"]] = colors

    if not entries:
        sys.exit("error: no chassis with a resolvable default palette - wrong SDB?")

    lines = [HEADER.rstrip("\n").replace("__PATCH__", db.patch)]
    for chassis_id in sorted(entries):
        colors = entries[chassis_id]
        cells = ", ".join(f"0x{c:08x}u" for c in colors)
        lines.append(f"        [{chassis_id}u] = [{cells}],")
    lines.append(FOOTER.replace("__PATCH__", db.patch).lstrip("\n"))

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\r\n") as fh:
        fh.write("\n".join(lines))

    print(f"wrote {args.out} ({len(entries)} chassis, SDB patch {db.patch})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
