#!/usr/bin/env python3
"""Generate the stock battleframe loadout table shared by the web hosts.

Every character PIN zones in owns at least the battleframe it was created with,
and the gear that frame ships with is authored in the static database:

    dbcharacter::CharCreateLoadout      (frame_id, id, is_starting_loadout,
                                         is_dev, name)
    dbcharacter::CharCreateLoadoutSlots (loadout_id, slot_type,
                                         default_pve_module,
                                         default_pvp_module)
    dbitems::RootItem                   (sdb_id, required_level)

The GameServer reads those tables at runtime (it has the SDB), but the web
hosts do not: they answer the character selection screen, the bag/gear
inventories and the garage. This tool precomputes one row per chassis so both
surfaces describe the same character ("get what you select"), the same way
``chassis_warpaints.py`` precomputes the armor colors.

Which loadout is a frame's *stock* one is the part that matters, because the
SDB carries several per frame and they are not variations of each other — they
are different tiers of the same frame:

* ``Accord <frame> - Player`` (the five Accord frames, flagged
  ``is_starting_loadout``): the starter kit, required level 1.
* ``<frame> Test Stage N Loadout``: another required-level-1 kit, the only
  complete one the advanced frames have in the slots PIN equips.
* ``Elite <frame> Reward Loadout``: the endgame unlock kit, every module at
  required level 20 — the one the dev sandbox handed to everybody, and the
  reason a new character used to look level-capped.
* ``Migration 40 <frame> Loadout``: the same at required level 40.
* ``Astrek "<frame>" - Player`` / ``ODM "<frame>" - Player``: the advanced
  frames' PvP kit. Its PvE gear is in slots 140-156 (a per-frame-level ladder
  from required level 21 upwards) and its weapon/ability slots carry PvP
  modules only, so a PvE character built from it would be unarmed.

The rule is therefore "the lowest tier that still gears a player":

1. skip every dev loadout and every loadout whose PvE modules do not fill a
   single slot the GameServer equips (weapons, abilities, chassis gear — the
   backpack is resolved from the chassis separately);
2. the loadout flagged ``is_starting_loadout`` wins (the Accord starter kit);
3. otherwise the lowest required level among those modules wins — a level 1
   kit before the level 20 reward one;
4. then the most equipped modules (a fuller kit beats a partial one);
5. then a ``- Player`` name;
6. then the lowest loadout id.

Usage:
    python3 chassis_loadouts.py [--sdb PATH] [--out PATH]

``--sdb`` defaults to ``Tools/clientdb.sd2`` when it exists, otherwise the
split archive ``Tools/clientdb.zip.001``/``.002`` is assembled in a temp
directory. ``--out`` defaults to
``Lib/Shared.Common/Characters/ChassisStockLoadouts.cs``.

Run it whenever the shipped ``clientdb.sd2`` changes; the generated file
carries the SDB patch string it was built from, so a stale table is visible.
"""

import argparse
import os
import sys
import tempfile
import zipfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sdb_dump import (  # noqa: E402
    StaticDB,
    _localized as localized,
    apply_column_names,
    harvest_pin_names,
)

TOOLS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO_ROOT = os.path.dirname(TOOLS_DIR)
GAME_SERVER_DIR = os.path.join(REPO_ROOT, "UdpHosts", "GameServer")
DEFAULT_OUT = os.path.join(REPO_ROOT, "Lib", "Shared.Common", "Characters",
                           "ChassisStockLoadouts.cs")

# A name ending in "- Player" is the frame's own player-facing loadout.
PLAYER_NAME_SUFFIX = "- Player"

# The slot types the GameServer equips from a char-create loadout
# (CharacterLoadout.LoadoutWeaponSlots + LoadoutAbilitySlots +
# LoadoutChassisSlots): weapons, abilities and chassis gear. The backpack is
# resolved from the chassis itself, and the legacy slot types (3, 4, 5, 10, and
# the frame-level ladder at 140-156) are not equipped at all.
EQUIPPED_SLOT_TYPES = {1, 2, 6, 7, 8, 9, 116, 122, 123, 124, 126, 127, 128, 129, 130, 137}

HEADER = '''//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by Tools/SdbDump/chassis_loadouts.py from clientdb.sd2 (patch __PATCH__).
//     Do not edit by hand; re-run the generator when the SDB changes:
//         python3 Tools/SdbDump/chassis_loadouts.py
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Shared.Common.Characters;

/// <summary>
/// The loadout each battleframe chassis ships with for a player in the static
/// database (build __PATCH__): <c>dbcharacter::CharCreateLoadout</c> joined with
/// <c>dbcharacter::CharCreateLoadoutSlots</c> and <c>dbitems::RootItem</c>,
/// picking per chassis the lowest tier that still gears a player — the loadout
/// flagged <c>is_starting_loadout</c> (the five Accord frames' required-level-1
/// starter kit), else the one whose equipped PvE modules ask for the lowest
/// required level (a level 1 kit rather than the <c>Elite ... Reward</c> kit
/// every module of which wants level 20, or the <c>Migration 40</c> one that
/// wants 40), preferring the fuller kit, then a <c>- Player</c> name, then the
/// lowest loadout id. Every dev loadout is skipped, and so is any loadout whose
/// PvE modules fill none of the slots a character wears — which is what rules
/// out the advanced frames' PvP loadouts (their PvE gear sits in slots 140-156,
/// a per-frame-level ladder, and their weapon slots carry PvP modules only).
/// <para>
/// The web hosts cannot read the SDB at runtime, so they use this table to
/// describe what a character owns: the gear the selection screen shows on a
/// character card, the equipped items behind
/// <c>api/v3/characters/{id}/inventories/gear/items</c> and the battleframe
/// slots of <c>api/v3/characters/{id}/garage_slots</c>. The GameServer reads
/// the same tables from the SDB through
/// <c>SDBUtils.GetStockCharCreateLoadout</c>, which applies the same rule, so
/// the character you select is the character you spawn as.
/// </para>
/// <para>
/// A chassis the table does not know (no non-dev loadout with gear at all) is
/// absent on purpose: such a character is equipped with its bare chassis and
/// the GameServer's default SDB colors.
/// </para>
/// </summary>
public static class ChassisStockLoadouts
{
    /// <summary>
    /// The stock loadout per chassis, indexed by the chassis SDB id, or null
    /// when the chassis carries none.
    /// </summary>
    public static IReadOnlyDictionary<uint, ChassisStockLoadout> ByChassis { get; } = new Dictionary<uint, ChassisStockLoadout>
    {
'''

FOOTER = '''    };

    /// <summary>The chassis' stock loadout, or false when it carries none.</summary>
    public static bool TryGet(uint chassisId, out ChassisStockLoadout loadout)
    {
        if (ByChassis.TryGetValue(chassisId, out loadout))
        {
            return true;
        }

        loadout = null;
        return false;
    }
}

/// <summary>
/// The gear one battleframe chassis ships with: the char-create loadout row it
/// was taken from and the modules slotted in it.
/// </summary>
public sealed class ChassisStockLoadout
{
    /// <summary>Chassis (battleframe) SDB id this loadout belongs to.</summary>
    public uint ChassisId { get; init; }

    /// <summary><c>dbcharacter::CharCreateLoadout</c> id the gear was read from.</summary>
    public uint LoadoutId { get; init; }

    /// <summary>
    /// The SDB row's own name, which names the tier the kit belongs to — e.g.
    /// <c>Accord Firecat - Player</c> or <c>Firecat Test Stage 2 Loadout</c>.
    /// </summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>
    /// The frame's own name — the chassis item's localized name, e.g.
    /// <c>Firecat</c> — which is what the client calls it in the garage. The
    /// loadout row's <see cref="Name"/> names the tier it belongs to
    /// (<c>Firecat Test Stage 2 Loadout</c>), not something to show a player.
    /// </summary>
    public string DisplayName { get; init; } = string.Empty;

    /// <summary>Whether the SDB flags this as a starting loadout (the Accord frames).</summary>
    public bool IsStartingLoadout { get; init; }

    /// <summary>The modules the loadout slots, ordered by slot type.</summary>
    public IReadOnlyList<StockLoadoutSlot> Slots { get; init; } = [];
}

/// <summary>One slotted module of a <see cref="ChassisStockLoadout"/>.</summary>
public sealed class StockLoadoutSlot
{
    /// <summary>
    /// Loadout slot this module goes into, the SDB's <c>slot_type</c>: the same
    /// numbering as the GameServer's <c>LoadoutSlotType</c> (1 = primary weapon,
    /// 2 = secondary, 6 = HKM, 7..9 = abilities, 11 = backpack, 116/122..129 =
    /// chassis gear).
    /// </summary>
    public byte SlotType { get; init; }

    /// <summary>Item SDB id worn in the PvE configuration (0 when the slot is empty).</summary>
    public uint PveModule { get; init; }

    /// <summary>Item SDB id worn in the PvP configuration (0 when the slot is empty).</summary>
    public uint PvpModule { get; init; }
}
'''


def cs_string(value):
    """A C# string literal for an SDB name (they carry embedded quotes)."""
    escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
    return f"\"{escaped}\""


def equipped_kit(modules, root):
    """(how many equipped PvE modules, the highest required level of them)."""
    levels = [root.get(m, {}).get("required_level", 0) or 0 for m in modules]
    return len(levels), (max(levels) if levels else 0)


def pick_loadout(candidates):
    """The frame's stock loadout: the lowest tier that still gears a player.

    `candidates` are `(loadout, count, highest_required_level)` triples of the
    frame's non-dev loadouts that equip at least one PvE module. Returns None
    when there are none.
    """
    if not candidates:
        return None

    def rank(entry):
        loadout, count, highest = entry
        return (
            0 if loadout["is_starting_loadout"] else 1,
            highest,
            -count,
            0 if str(loadout["name"]).endswith(PLAYER_NAME_SUFFIX) else 1,
            loadout["id"],
        )

    return sorted(candidates, key=rank)[0][0]


def display_name(name):
    """'Astrek "Firecat" - Player' -> 'Astrek "Firecat"'."""
    name = str(name).strip()
    if name.endswith(PLAYER_NAME_SUFFIX):
        return name[: -len(PLAYER_NAME_SUFFIX)].strip()
    return name


def collect(db):
    """chassis id -> the frame's stock loadout plus its slotted modules."""
    loadouts = list(db.rows(db.find_table("dbcharacter::CharCreateLoadout")))
    slots = list(db.rows(db.find_table("dbcharacter::CharCreateLoadoutSlots")))
    frames = {row["id"] for row in db.rows(db.find_table("dbitems::Battleframe"))}
    root = {row["sdb_id"]: row for row in db.rows(db.find_table("dbitems::RootItem"))}

    by_loadout = {}
    for slot in slots:
        by_loadout.setdefault(slot["loadout_id"], []).append(slot)

    by_frame = {}
    for row in loadouts:
        if row["is_dev"] or row["frame_id"] not in frames:
            continue
        equipped = [s["default_pve_module"] for s in by_loadout.get(row["id"], [])
                    if s["slot_type"] in EQUIPPED_SLOT_TYPES and s["default_pve_module"]]
        count, highest = equipped_kit(equipped, root)
        if count == 0:
            # Nothing a PvE character could wear: the dev rows, the social and
            # civilian entries, and the advanced frames' PvP-only loadouts.
            continue
        by_frame.setdefault(row["frame_id"], []).append((row, count, highest))

    table = {}
    for chassis in sorted(by_frame):
        chosen = pick_loadout(by_frame[chassis])
        if chosen is None:
            continue
        table[chassis] = {
            "loadout": chosen,
            "slots": sorted(by_loadout.get(chosen["id"], []),
                            key=lambda s: s["slot_type"]),
        }

    # The frame's own name, which is what the client calls it in the garage
    # ("Firecat", "Dreadnaught"): the loadout row's name is the tier it belongs
    # to ("Firecat Test Stage 2 Loadout"), not something to show a player.
    needed = {cid: root[cid]["name_id"] for cid in table if cid in root}
    names = localized(db, set(needed.values()))
    for cid, name_id in needed.items():
        table[cid]["display"] = names.get(name_id) or display_name(table[cid]["loadout"]["name"])

    return table


def render(table, patch):
    out = [HEADER.replace("__PATCH__", patch)]
    for chassis in sorted(table):
        entry = table[chassis]
        loadout = entry["loadout"]
        out.append(f"        [{chassis}u] = new ChassisStockLoadout\n")
        out.append("                  {\n")
        out.append(f"                      ChassisId = {chassis}u,\n")
        out.append(f"                      LoadoutId = {loadout['id']}u,\n")
        out.append(f"                      Name = {cs_string(loadout['name'])},\n")
        out.append(f"                      DisplayName = {cs_string(entry.get('display') or display_name(loadout['name']))},\n")
        out.append(f"                      IsStartingLoadout = {'true' if loadout['is_starting_loadout'] else 'false'},\n")
        out.append("                      Slots =\n")
        out.append("                      [\n")
        for slot in entry["slots"]:
            out.append(
                "                          new StockLoadoutSlot "
                + "{ SlotType = %d, PveModule = %du, PvpModule = %du },\n"
                % (slot["slot_type"], slot["default_pve_module"], slot["default_pvp_module"]))
        out.append("                      ]\n")
        out.append("                  },\n")
    out.append(FOOTER)
    return "".join(out)


def find_sdb(explicit):
    if explicit:
        if not os.path.isfile(explicit):
            sys.exit(f"error: no SDB file at {explicit}")
        return explicit

    direct = os.path.join(TOOLS_DIR, "clientdb.sd2")
    if os.path.isfile(direct):
        return direct

    parts = [os.path.join(TOOLS_DIR, "clientdb.zip.001"),
             os.path.join(TOOLS_DIR, "clientdb.zip.002")]
    if not all(os.path.isfile(p) for p in parts):
        sys.exit("error: pass --sdb PATH to clientdb.sd2 (the split "
                 "Tools/clientdb.zip.001/.002 archive was not found)")

    # The assembly must outlive this function, so it goes to the system temp
    # dir (fixed name, overwritten on each run) rather than a context-managed
    # temp directory.
    extracted = os.path.join(tempfile.gettempdir(), "pin_chassis_loadouts_clientdb.sd2")
    assembled = os.path.join(tempfile.gettempdir(), "pin_chassis_loadouts_clientdb.zip")
    with open(assembled, "wb") as out:
        for part in parts:
            with open(part, "rb") as fh:
                out.write(fh.read())
    with zipfile.ZipFile(assembled) as z:
        members = [n for n in z.namelist() if n.endswith(".sd2")]
        if not members:
            sys.exit(f"error: no .sd2 member in {parts}")
        with z.open(members[0]) as src, open(extracted, "wb") as dst:
            dst.write(src.read())
    return extracted


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--sdb", help="path to clientdb.sd2 (default: Tools/)")
    parser.add_argument("--out", default=DEFAULT_OUT,
                        help="where to write the generated C# file")
    args = parser.parse_args(argv)

    path = find_sdb(args.sdb)
    db = StaticDB(path)
    table_names, columns = harvest_pin_names(GAME_SERVER_DIR)
    db.resolve_names(table_names)
    apply_column_names(db, columns)

    table = collect(db)
    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render(table, db.patch))
    print(f"wrote {args.out} ({len(table)} chassis, SDB patch {db.patch})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
