using System.Linq;
using Shared.Common.Characters;
using Xunit;

namespace GameServer.Tests;

/// <summary>
///     Tests for the precomputed stock battleframe loadout table
///     (<see cref="ChassisStockLoadouts"/>, generated by
///     <c>Tools/SdbDump/chassis_loadouts.py</c>) and the filter that turns one
///     into the gear a character wears (<see cref="StockLoadoutSlots"/>).
/// </summary>
/// <remarks>
///     The table is what the web hosts describe a character with — they cannot
///     read the static database at runtime — and the GameServer applies the same
///     rule to the SDB at login (<c>SDBUtils.GetStockCharCreateLoadout</c>), so
///     these tests are also the ones that pin "a fresh character starts in its
///     frame's own starter gear, not in the operator's endgame kit".
/// </remarks>
public class ChassisStockLoadoutsTests
{
    /// <summary>Accord Dreadnaught — one of the five frames the creation screen offers.</summary>
    private const uint AccordDreadnaught = 75772u;

    /// <summary>Astrek "Firecat" — an advanced frame.</summary>
    private const uint Firecat = 76133u;

    /// <summary>Astrek "Raptor" — the chassis the hardcoded default character wears.</summary>
    private const uint Raptor = 76334u;

    [Fact]
    public void TryGet_CarriesTheAccordStarterKit()
    {
        Assert.True(ChassisStockLoadouts.TryGet(AccordDreadnaught, out var dreadnaught));

        // The five Accord frames are the ones the static database flags as a
        // starting loadout: their kit is what a new character of the frame gets.
        Assert.True(dreadnaught.IsStartingLoadout);
        Assert.Equal(1u, dreadnaught.LoadoutId);
        Assert.Equal("Dreadnaught", dreadnaught.DisplayName);

        // A kit a character can fight with: a primary, a secondary and a HKM.
        Assert.Contains(dreadnaught.Slots, slot => slot.SlotType == 1 && slot.PveModule != 0);
        Assert.Contains(dreadnaught.Slots, slot => slot.SlotType == 2 && slot.PveModule != 0);
        Assert.Contains(dreadnaught.Slots, slot => slot.SlotType == 6 && slot.PveModule != 0);
    }

    [Fact]
    public void TryGet_NamesTheFrameNotTheLoadoutRow()
    {
        // The loadout row is named after the tier it belongs to ("Firecat Test
        // Stage 2 Loadout"), the garage needs the frame's own name.
        Assert.True(ChassisStockLoadouts.TryGet(Firecat, out var firecat));
        Assert.Equal("Firecat", firecat.DisplayName);

        Assert.True(ChassisStockLoadouts.TryGet(Raptor, out var raptor));
        Assert.Equal("Raptor", raptor.DisplayName);
    }

    [Fact]
    public void TryGet_IsAbsentForAChassisNoPlayerLoadoutBelongsTo()
    {
        Assert.False(ChassisStockLoadouts.TryGet(1u, out var loadout));
        Assert.Null(loadout);
    }

    [Fact]
    public void GearFor_FiltersTheLoadoutDownToTheSlotsACharacterWears()
    {
        var gear = StockLoadoutSlots.GearFor(Firecat);

        Assert.NotEmpty(gear);
        Assert.All(gear, slot => Assert.True(StockLoadoutSlots.IsEquipped(slot.SlotType)));

        // The legacy slot types (3, 4, 5, 10) and the frame-level ladder the
        // advanced frames keep their PvE gear in (140 and up) are not equipped.
        Assert.DoesNotContain(gear, slot => slot.SlotType is 3 or 4 or 5 or 10 or 140);
    }

    [Fact]
    public void GearFor_IsEmptyForAnUnknownChassis()
    {
        Assert.Empty(StockLoadoutSlots.GearFor(1u));
    }
}
