//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by Tools/SdbDump/chassis_loadouts.py from clientdb.sd2 (patch prod-1962).
//     Do not edit by hand; re-run the generator when the SDB changes:
//         python3 Tools/SdbDump/chassis_loadouts.py
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace Shared.Common.Characters;

/// <summary>
/// The loadout each battleframe chassis ships with for a player in the static
/// database (build prod-1962): <c>dbcharacter::CharCreateLoadout</c> joined with
/// <c>dbcharacter::CharCreateLoadoutSlots</c> and <c>dbitems::RootItem</c>,
/// picking per chassis the lowest tier that still gears a player — the loadout
/// flagged <c>is_starting_loadout</c> (the five Accord frames' required-level-1
/// starter kit), else the one whose equipped PvE modules ask for the lowest
/// required level (a level 1 kit rather than the <c>Elite ... Reward</c> kit
/// every module of which wants level 20, or the <c>Migration 40</c> one that
/// wants 40), preferring the fuller kit, then a <c>- Player</c> name, then the
/// lowest loadout id. Every dev loadout is skipped, and so is any loadout whose
/// PvE modules fill none of the slots a character wears — which is what rules
/// out the advanced frames' PvP loadouts (their PvE gear sits in slots 140-156,
/// a per-frame-level ladder, and their weapon slots carry PvP modules only).
/// <para>
/// The web hosts cannot read the SDB at runtime, so they use this table to
/// describe what a character owns: the gear the selection screen shows on a
/// character card, the equipped items behind
/// <c>api/v3/characters/{id}/inventories/gear/items</c> and the battleframe
/// slots of <c>api/v3/characters/{id}/garage_slots</c>. The GameServer reads
/// the same tables from the SDB through
/// <c>SDBUtils.GetStockCharCreateLoadout</c>, which applies the same rule, so
/// the character you select is the character you spawn as.
/// </para>
/// <para>
/// A chassis the table does not know (no non-dev loadout with gear at all) is
/// absent on purpose: such a character is equipped with its bare chassis and
/// the GameServer's default SDB colors.
/// </para>
/// </summary>
public static class ChassisStockLoadouts
{
    /// <summary>
    /// The stock loadout per chassis, indexed by the chassis SDB id, or null
    /// when the chassis carries none.
    /// </summary>
    public static IReadOnlyDictionary<uint, ChassisStockLoadout> ByChassis { get; } = new Dictionary<uint, ChassisStockLoadout>
    {
        [75683u] = new ChassisStockLoadout
                  {
                      ChassisId = 75683u,
                      LoadoutId = 53u,
                      Name = "Assault Test Stage 3 loadout",
                      DisplayName = "Accord Assaultframe",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 77949u, PvpModule = 77949u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 78495u, PvpModule = 78495u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78528u, PvpModule = 78528u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78925u, PvpModule = 78925u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 78518u, PvpModule = 78518u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 78512u, PvpModule = 78512u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 78507u, PvpModule = 78507u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 78503u, PvpModule = 78503u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 82745u, PvpModule = 78499u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 78522u, PvpModule = 78522u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 76022u, PvpModule = 76022u },
                      ]
                  },
        [75772u] = new ChassisStockLoadout
                  {
                      ChassisId = 75772u,
                      LoadoutId = 1u,
                      Name = "Accord Dreadnaught - Player",
                      DisplayName = "Dreadnaught",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 86851u, PvpModule = 124644u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 87800u, PvpModule = 136318u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 125199u, PvpModule = 143251u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 0u, PvpModule = 124143u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 0u, PvpModule = 139922u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 0u, PvpModule = 124144u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 75873u, PvpModule = 143207u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 126000u, PvpModule = 130606u },
                          new StockLoadoutSlot { SlotType = 117, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 121, PveModule = 90493u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 122, PveModule = 129505u, PvpModule = 130596u },
                          new StockLoadoutSlot { SlotType = 123, PveModule = 0u, PvpModule = 130599u },
                          new StockLoadoutSlot { SlotType = 124, PveModule = 0u, PvpModule = 130597u },
                          new StockLoadoutSlot { SlotType = 126, PveModule = 127501u, PvpModule = 130595u },
                          new StockLoadoutSlot { SlotType = 127, PveModule = 128271u, PvpModule = 130598u },
                          new StockLoadoutSlot { SlotType = 128, PveModule = 126731u, PvpModule = 130602u },
                          new StockLoadoutSlot { SlotType = 129, PveModule = 129067u, PvpModule = 130600u },
                          new StockLoadoutSlot { SlotType = 130, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 132, PveModule = 91296u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 133, PveModule = 123309u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 134, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 137, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 138, PveModule = 125285u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 139, PveModule = 91024u, PvpModule = 0u },
                      ]
                  },
        [75773u] = new ChassisStockLoadout
                  {
                      ChassisId = 75773u,
                      LoadoutId = 7u,
                      Name = "Accord Recon - Player",
                      DisplayName = "Recon",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 86969u, PvpModule = 124640u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 87918u, PvpModule = 142331u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 91770u, PvpModule = 124155u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 0u, PvpModule = 124153u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 0u, PvpModule = 141527u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 0u, PvpModule = 140773u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 75876u, PvpModule = 143204u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 126000u, PvpModule = 130606u },
                          new StockLoadoutSlot { SlotType = 117, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 121, PveModule = 91662u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 122, PveModule = 129359u, PvpModule = 130596u },
                          new StockLoadoutSlot { SlotType = 123, PveModule = 0u, PvpModule = 130599u },
                          new StockLoadoutSlot { SlotType = 124, PveModule = 0u, PvpModule = 130597u },
                          new StockLoadoutSlot { SlotType = 126, PveModule = 127501u, PvpModule = 130595u },
                          new StockLoadoutSlot { SlotType = 127, PveModule = 128271u, PvpModule = 130598u },
                          new StockLoadoutSlot { SlotType = 128, PveModule = 126731u, PvpModule = 130602u },
                          new StockLoadoutSlot { SlotType = 129, PveModule = 129067u, PvpModule = 130600u },
                          new StockLoadoutSlot { SlotType = 130, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 132, PveModule = 90285u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 133, PveModule = 90020u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 134, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 137, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 138, PveModule = 125285u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 139, PveModule = 91793u, PvpModule = 0u },
                      ]
                  },
        [75774u] = new ChassisStockLoadout
                  {
                      ChassisId = 75774u,
                      LoadoutId = 3u,
                      Name = "Accord Biotech - Player",
                      DisplayName = "Biotech",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 87028u, PvpModule = 143147u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 87918u, PvpModule = 142135u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 89124u, PvpModule = 143154u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 0u, PvpModule = 124158u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 0u, PvpModule = 143153u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 0u, PvpModule = 143152u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 75874u, PvpModule = 143203u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 126000u, PvpModule = 130606u },
                          new StockLoadoutSlot { SlotType = 117, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 121, PveModule = 123271u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 122, PveModule = 129213u, PvpModule = 130596u },
                          new StockLoadoutSlot { SlotType = 123, PveModule = 0u, PvpModule = 130599u },
                          new StockLoadoutSlot { SlotType = 124, PveModule = 0u, PvpModule = 130597u },
                          new StockLoadoutSlot { SlotType = 126, PveModule = 127501u, PvpModule = 130595u },
                          new StockLoadoutSlot { SlotType = 127, PveModule = 128271u, PvpModule = 130598u },
                          new StockLoadoutSlot { SlotType = 128, PveModule = 126731u, PvpModule = 130602u },
                          new StockLoadoutSlot { SlotType = 129, PveModule = 129067u, PvpModule = 130600u },
                          new StockLoadoutSlot { SlotType = 130, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 132, PveModule = 88808u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 133, PveModule = 123262u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 134, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 137, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 138, PveModule = 125285u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 139, PveModule = 89147u, PvpModule = 0u },
                      ]
                  },
        [75775u] = new ChassisStockLoadout
                  {
                      ChassisId = 75775u,
                      LoadoutId = 5u,
                      Name = "Accord Engineer - Player",
                      DisplayName = "Engineer",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 87386u, PvpModule = 124533u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 87978u, PvpModule = 142119u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 91559u, PvpModule = 124151u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 0u, PvpModule = 124148u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 0u, PvpModule = 141258u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 0u, PvpModule = 124150u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 31344u, PvpModule = 143206u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 126000u, PvpModule = 130606u },
                          new StockLoadoutSlot { SlotType = 117, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 121, PveModule = 91394u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 122, PveModule = 129359u, PvpModule = 130596u },
                          new StockLoadoutSlot { SlotType = 123, PveModule = 0u, PvpModule = 130599u },
                          new StockLoadoutSlot { SlotType = 124, PveModule = 0u, PvpModule = 130597u },
                          new StockLoadoutSlot { SlotType = 126, PveModule = 127501u, PvpModule = 130595u },
                          new StockLoadoutSlot { SlotType = 127, PveModule = 128271u, PvpModule = 130598u },
                          new StockLoadoutSlot { SlotType = 128, PveModule = 126731u, PvpModule = 130602u },
                          new StockLoadoutSlot { SlotType = 129, PveModule = 129067u, PvpModule = 130600u },
                          new StockLoadoutSlot { SlotType = 130, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 132, PveModule = 131211u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 133, PveModule = 91510u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 134, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 137, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 138, PveModule = 125285u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 139, PveModule = 91582u, PvpModule = 0u },
                      ]
                  },
        [76132u] = new ChassisStockLoadout
                  {
                      ChassisId = 76132u,
                      LoadoutId = 57u,
                      Name = "Tigerclaw Test Stage 3 Loadout",
                      DisplayName = "Tigerclaw",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 79339u, PvpModule = 79339u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 78495u, PvpModule = 78495u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78528u, PvpModule = 78528u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78925u, PvpModule = 78925u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 79942u, PvpModule = 79942u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 78850u, PvpModule = 78850u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 79934u, PvpModule = 79934u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 79938u, PvpModule = 79938u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 79930u, PvpModule = 79930u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 79946u, PvpModule = 79946u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 76022u, PvpModule = 76022u },
                      ]
                  },
        [76133u] = new ChassisStockLoadout
                  {
                      ChassisId = 76133u,
                      LoadoutId = 98u,
                      Name = "Firecat Test Stage 2 Loadout (st",
                      DisplayName = "Firecat",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 79305u, PvpModule = 79305u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 78494u, PvpModule = 78494u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78525u, PvpModule = 78525u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78924u, PvpModule = 78924u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 78517u, PvpModule = 78517u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 78554u, PvpModule = 78554u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 78542u, PvpModule = 78542u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 78536u, PvpModule = 78536u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 78548u, PvpModule = 78548u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 78565u, PvpModule = 78565u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 75877u, PvpModule = 75877u },
                      ]
                  },
        [76164u] = new ChassisStockLoadout
                  {
                      ChassisId = 76164u,
                      LoadoutId = 2u,
                      Name = "Accord Assault - Player",
                      DisplayName = "Assault",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 86742u, PvpModule = 124651u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 87741u, PvpModule = 142132u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 88491u, PvpModule = 124142u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 0u, PvpModule = 143211u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 0u, PvpModule = 124140u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 0u, PvpModule = 124132u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 75877u, PvpModule = 143205u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 126000u, PvpModule = 130606u },
                          new StockLoadoutSlot { SlotType = 117, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 121, PveModule = 88039u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 122, PveModule = 129213u, PvpModule = 130596u },
                          new StockLoadoutSlot { SlotType = 123, PveModule = 0u, PvpModule = 130599u },
                          new StockLoadoutSlot { SlotType = 124, PveModule = 0u, PvpModule = 130597u },
                          new StockLoadoutSlot { SlotType = 126, PveModule = 127501u, PvpModule = 130595u },
                          new StockLoadoutSlot { SlotType = 127, PveModule = 128271u, PvpModule = 130598u },
                          new StockLoadoutSlot { SlotType = 128, PveModule = 126731u, PvpModule = 130602u },
                          new StockLoadoutSlot { SlotType = 129, PveModule = 129067u, PvpModule = 130600u },
                          new StockLoadoutSlot { SlotType = 130, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 132, PveModule = 88099u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 133, PveModule = 88324u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 134, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 137, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 138, PveModule = 125285u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 139, PveModule = 88514u, PvpModule = 0u },
                      ]
                  },
        [76331u] = new ChassisStockLoadout
                  {
                      ChassisId = 76331u,
                      LoadoutId = 102u,
                      Name = "Mammoth Test Stage 2 Loadout",
                      DisplayName = "Mammoth",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 78490u, PvpModule = 78490u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 78494u, PvpModule = 78494u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78525u, PvpModule = 78525u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78924u, PvpModule = 78924u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 78748u, PvpModule = 78748u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 78743u, PvpModule = 78743u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 78739u, PvpModule = 78739u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 78734u, PvpModule = 78734u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 78728u, PvpModule = 78728u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 79965u, PvpModule = 79965u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 75873u, PvpModule = 75873u },
                      ]
                  },
        [76332u] = new ChassisStockLoadout
                  {
                      ChassisId = 76332u,
                      LoadoutId = 65u,
                      Name = "Rhino Test Stage 3 Loadout",
                      DisplayName = "Rhino",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 78754u, PvpModule = 78754u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 78495u, PvpModule = 78495u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78528u, PvpModule = 78528u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78528u, PvpModule = 78528u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 85206u, PvpModule = 85206u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 78779u, PvpModule = 78779u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 78768u, PvpModule = 78768u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 78759u, PvpModule = 78759u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 78773u, PvpModule = 78773u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 82842u, PvpModule = 82842u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 76018u, PvpModule = 76018u },
                      ]
                  },
        [76333u] = new ChassisStockLoadout
                  {
                      ChassisId = 76333u,
                      LoadoutId = 61u,
                      Name = "Nighthawk Test Stage 3 Loadout",
                      DisplayName = "Nighthawk",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 78889u, PvpModule = 78889u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 79085u, PvpModule = 79085u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78528u, PvpModule = 78528u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78925u, PvpModule = 78925u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 79974u, PvpModule = 79974u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 78909u, PvpModule = 78909u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 78904u, PvpModule = 78904u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 78900u, PvpModule = 78900u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 78895u, PvpModule = 78895u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 79978u, PvpModule = 79978u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 76021u, PvpModule = 76021u },
                      ]
                  },
        [76334u] = new ChassisStockLoadout
                  {
                      ChassisId = 76334u,
                      LoadoutId = 66u,
                      Name = "Raptor Test Stage 3 Loadout",
                      DisplayName = "Raptor",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 78883u, PvpModule = 78435u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 79085u, PvpModule = 78061u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78528u, PvpModule = 78071u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78925u, PvpModule = 78069u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 78858u, PvpModule = 78399u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 79004u, PvpModule = 78443u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 79000u, PvpModule = 78441u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 79008u, PvpModule = 78437u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 79012u, PvpModule = 78439u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 79986u, PvpModule = 78445u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 76021u, PvpModule = 76021u },
                      ]
                  },
        [76335u] = new ChassisStockLoadout
                  {
                      ChassisId = 76335u,
                      LoadoutId = 63u,
                      Name = "Dragonfly Test Stage 3 Loadout",
                      DisplayName = "Dragonfly",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 79041u, PvpModule = 79041u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 79089u, PvpModule = 79089u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78528u, PvpModule = 78528u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78925u, PvpModule = 78925u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 79036u, PvpModule = 79036u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 78844u, PvpModule = 78844u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 79056u, PvpModule = 79056u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 79046u, PvpModule = 79046u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 79051u, PvpModule = 79051u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 79990u, PvpModule = 79990u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 76019u, PvpModule = 76019u },
                      ]
                  },
        [76336u] = new ChassisStockLoadout
                  {
                      ChassisId = 76336u,
                      LoadoutId = 110u,
                      Name = "Recluse Test Stage 2 Loadout",
                      DisplayName = "Recluse",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 79059u, PvpModule = 79059u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 78494u, PvpModule = 78494u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78525u, PvpModule = 78525u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78924u, PvpModule = 78924u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 79035u, PvpModule = 79035u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 79076u, PvpModule = 79076u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 79068u, PvpModule = 79068u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 79063u, PvpModule = 79063u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 79072u, PvpModule = 79072u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 79080u, PvpModule = 79080u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 75874u, PvpModule = 75874u },
                      ]
                  },
        [76337u] = new ChassisStockLoadout
                  {
                      ChassisId = 76337u,
                      LoadoutId = 64u,
                      Name = "Electron Test Stage 3 Loadout",
                      DisplayName = "Electron",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 79050u, PvpModule = 79050u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 78495u, PvpModule = 78495u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78528u, PvpModule = 78528u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78925u, PvpModule = 78925u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 79954u, PvpModule = 79954u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 78671u, PvpModule = 78671u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 78666u, PvpModule = 78666u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 78660u, PvpModule = 78660u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 78654u, PvpModule = 78654u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 79950u, PvpModule = 79950u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 76020u, PvpModule = 76020u },
                      ]
                  },
        [76338u] = new ChassisStockLoadout
                  {
                      ChassisId = 76338u,
                      LoadoutId = 59u,
                      Name = "Bastion Test Stage 3 Loadout",
                      DisplayName = "Bastion",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 79101u, PvpModule = 79101u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 79089u, PvpModule = 79089u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78528u, PvpModule = 78528u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78925u, PvpModule = 78925u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 79962u, PvpModule = 79962u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 78706u, PvpModule = 78706u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 78700u, PvpModule = 78700u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 78693u, PvpModule = 78693u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 78687u, PvpModule = 78687u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 78723u, PvpModule = 78723u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 76020u, PvpModule = 76020u },
                      ]
                  },
        [82359u] = new ChassisStockLoadout
                  {
                      ChassisId = 82359u,
                      LoadoutId = 47u,
                      Name = "Kisuton \"Graviton\"",
                      DisplayName = "KS-G01 \"Graviton\"",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 77083u, PvpModule = 83449u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 0u, PvpModule = 79066u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78070u, PvpModule = 78070u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78068u, PvpModule = 78069u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 78418u, PvpModule = 78419u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 0u, PvpModule = 83451u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 0u, PvpModule = 83454u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 0u, PvpModule = 83453u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 0u, PvpModule = 83452u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 82415u, PvpModule = 83450u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 75875u, PvpModule = 75875u },
                      ]
                  },
        [82360u] = new ChassisStockLoadout
                  {
                      ChassisId = 82360u,
                      LoadoutId = 120u,
                      Name = "Arsenal Test Stage 1 Loadout",
                      DisplayName = "Arsenal",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 82403u, PvpModule = 83446u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 78493u, PvpModule = 78062u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78524u, PvpModule = 78524u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78921u, PvpModule = 78921u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 85405u, PvpModule = 85403u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 82486u, PvpModule = 83447u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 82365u, PvpModule = 82369u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 82372u, PvpModule = 82376u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 82379u, PvpModule = 82383u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 82490u, PvpModule = 83448u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 85464u, PvpModule = 85464u },
                      ]
                  },
        [82394u] = new ChassisStockLoadout
                  {
                      ChassisId = 82394u,
                      LoadoutId = 49u,
                      Name = "ODM \"Archangel\"",
                      DisplayName = "Archangel",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 82390u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 87741u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 82536u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 82521u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 82526u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 82531u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 78448u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 101763u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 117, PveModule = 90860u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 118, PveModule = 104882u, PvpModule = 0u },
                      ]
                  },
        [85694u] = new ChassisStockLoadout
                  {
                      ChassisId = 85694u,
                      LoadoutId = 119u,
                      Name = "NPE5 Astrek \"Firecat\"",
                      DisplayName = "A-43 \"Firecat\"",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 85675u, PvpModule = 85675u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 3, PveModule = 78070u, PvpModule = 78070u },
                          new StockLoadoutSlot { SlotType = 4, PveModule = 78068u, PvpModule = 78068u },
                          new StockLoadoutSlot { SlotType = 5, PveModule = 78078u, PvpModule = 78078u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 77773u, PvpModule = 77773u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 77127u, PvpModule = 77127u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 75273u, PvpModule = 75273u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 77726u, PvpModule = 77726u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 77902u, PvpModule = 77902u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 78448u, PvpModule = 78448u },
                          new StockLoadoutSlot { SlotType = 13, PveModule = 85729u, PvpModule = 85729u },
                      ]
                  },
        [95470u] = new ChassisStockLoadout
                  {
                      ChassisId = 95470u,
                      LoadoutId = 245u,
                      Name = "[CORE MISSIONS] Stealth Battlefr",
                      DisplayName = "Arc Content - Rebel Disguise - OUTLAW Assault Battleframe",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 0u, PvpModule = 79189u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 0u, PvpModule = 78061u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 0u, PvpModule = 78392u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 123440u, PvpModule = 78391u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 122627u, PvpModule = 78390u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 0u, PvpModule = 78389u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 0u, PvpModule = 78393u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 0u, PvpModule = 75876u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 0u, PvpModule = 0u },
                      ]
                  },
        [96744u] = new ChassisStockLoadout
                  {
                      ChassisId = 96744u,
                      LoadoutId = 225u,
                      Name = "Omnidyne Disguise",
                      DisplayName = "Omnidyne Civilian Combat - Thin 05",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 96457u, PvpModule = 79189u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 96458u, PvpModule = 78061u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 0u, PvpModule = 78392u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 0u, PvpModule = 78391u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 0u, PvpModule = 78390u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 0u, PvpModule = 78389u },
                          new StockLoadoutSlot { SlotType = 10, PveModule = 0u, PvpModule = 78393u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 0u, PvpModule = 75876u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 0u, PvpModule = 0u },
                      ]
                  },
        [123422u] = new ChassisStockLoadout
                  {
                      ChassisId = 123422u,
                      LoadoutId = 244u,
                      Name = "EXPERIMENTAL - PVP Accord Dreadn",
                      DisplayName = "PvP Dreadnaught",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 124644u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 136318u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 143251u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 139922u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 124144u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 124143u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 143207u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 130606u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 122, PveModule = 130596u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 123, PveModule = 130599u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 124, PveModule = 130597u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 126, PveModule = 130595u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 127, PveModule = 130598u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 128, PveModule = 130602u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 129, PveModule = 130600u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 130, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 137, PveModule = 0u, PvpModule = 0u },
                      ]
                  },
        [124681u] = new ChassisStockLoadout
                  {
                      ChassisId = 124681u,
                      LoadoutId = 322u,
                      Name = "PvP - MvS - Hunter - Minion",
                      DisplayName = "PvP - MvG - Hunter - Minion Frame",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 142070u, PvpModule = 142070u },
                      ]
                  },
        [124770u] = new ChassisStockLoadout
                  {
                      ChassisId = 124770u,
                      LoadoutId = 252u,
                      Name = "PvP - MvG - Survivor - Base",
                      DisplayName = "PvP - MvG - Survivor - Base Frame",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 140975u, PvpModule = 0u },
                      ]
                  },
        [124810u] = new ChassisStockLoadout
                  {
                      ChassisId = 124810u,
                      LoadoutId = 324u,
                      Name = "PvP - MvS - Soldier - Base",
                      DisplayName = "PvP - MvG - Soldier - Frame",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 142953u, PvpModule = 142953u },
                      ]
                  },
        [134400u] = new ChassisStockLoadout
                  {
                      ChassisId = 134400u,
                      LoadoutId = 272u,
                      Name = "PvP - MvG - Hunter - Overlord",
                      DisplayName = "PvP - MvG - Hunter - Overlord Frame",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 124759u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 124868u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 141850u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 124871u, PvpModule = 0u },
                      ]
                  },
        [138816u] = new ChassisStockLoadout
                  {
                      ChassisId = 138816u,
                      LoadoutId = 278u,
                      Name = "PvP - MvG - Survivor - With Jets",
                      DisplayName = "PvP - MvG - Survivor - Frame (With Jump Jets)",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 140975u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 138817u, PvpModule = 138817u },
                      ]
                  },
        [139120u] = new ChassisStockLoadout
                  {
                      ChassisId = 139120u,
                      LoadoutId = 279u,
                      Name = "PvP - MvG - Soldier - With Jets",
                      DisplayName = "PvP - MvG - Soldier - Frame (With Jump Jets)",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 138330u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 138817u, PvpModule = 138817u },
                          new StockLoadoutSlot { SlotType = 122, PveModule = 140941u, PvpModule = 0u },
                      ]
                  },
        [141554u] = new ChassisStockLoadout
                  {
                      ChassisId = 141554u,
                      LoadoutId = 318u,
                      Name = "EXPERIMENTAL - PvP Bastion",
                      DisplayName = "PvP Bastion",
                      IsStartingLoadout = false,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 141876u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 142119u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 142043u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 141609u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 142037u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 141612u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 143206u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 130606u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 122, PveModule = 130596u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 123, PveModule = 130599u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 124, PveModule = 130597u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 126, PveModule = 130595u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 127, PveModule = 130598u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 128, PveModule = 130602u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 129, PveModule = 130600u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 130, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 137, PveModule = 0u, PvpModule = 0u },
                      ]
                  },
        [142236u] = new ChassisStockLoadout
                  {
                      ChassisId = 142236u,
                      LoadoutId = 321u,
                      Name = "PvP - MvS - Hunter - Overlord",
                      DisplayName = "PvP - MvS - Hunter - Overlord Frame",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 142070u, PvpModule = 142070u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 142295u, PvpModule = 142295u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 142909u, PvpModule = 142909u },
                      ]
                  },
        [142772u] = new ChassisStockLoadout
                  {
                      ChassisId = 142772u,
                      LoadoutId = 326u,
                      Name = "PvP - MvS - Survivor - With Jets",
                      DisplayName = "PvP - MvS - Survivor - Frame (With Jump Jets)",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 142234u, PvpModule = 142234u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 142774u, PvpModule = 142774u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 138817u, PvpModule = 138817u },
                      ]
                  },
        [142773u] = new ChassisStockLoadout
                  {
                      ChassisId = 142773u,
                      LoadoutId = 327u,
                      Name = "PvP - MvS - Soldier - With Jets",
                      DisplayName = "PvP - MvS - Soldier - Frame (With Jump Jets)",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 142953u, PvpModule = 142953u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 138817u, PvpModule = 138817u },
                      ]
                  },
        [143117u] = new ChassisStockLoadout
                  {
                      ChassisId = 143117u,
                      LoadoutId = 329u,
                      Name = "TESTJumpheight",
                      DisplayName = "Do Not Translate - Jumpheight Test",
                      IsStartingLoadout = true,
                      Slots =
                      [
                          new StockLoadoutSlot { SlotType = 1, PveModule = 86742u, PvpModule = 79272u },
                          new StockLoadoutSlot { SlotType = 2, PveModule = 87741u, PvpModule = 79066u },
                          new StockLoadoutSlot { SlotType = 6, PveModule = 88491u, PvpModule = 78051u },
                          new StockLoadoutSlot { SlotType = 7, PveModule = 0u, PvpModule = 77639u },
                          new StockLoadoutSlot { SlotType = 8, PveModule = 0u, PvpModule = 78045u },
                          new StockLoadoutSlot { SlotType = 9, PveModule = 0u, PvpModule = 78042u },
                          new StockLoadoutSlot { SlotType = 11, PveModule = 75877u, PvpModule = 75877u },
                          new StockLoadoutSlot { SlotType = 116, PveModule = 126000u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 117, PveModule = 88070u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 121, PveModule = 123063u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 122, PveModule = 129213u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 123, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 124, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 126, PveModule = 127501u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 127, PveModule = 128271u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 128, PveModule = 126731u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 129, PveModule = 129067u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 130, PveModule = 143118u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 132, PveModule = 88321u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 133, PveModule = 88102u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 134, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 137, PveModule = 0u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 138, PveModule = 125285u, PvpModule = 0u },
                          new StockLoadoutSlot { SlotType = 139, PveModule = 88514u, PvpModule = 0u },
                      ]
                  },
    };

    /// <summary>The chassis' stock loadout, or false when it carries none.</summary>
    public static bool TryGet(uint chassisId, out ChassisStockLoadout loadout)
    {
        if (ByChassis.TryGetValue(chassisId, out loadout))
        {
            return true;
        }

        loadout = null;
        return false;
    }
}

/// <summary>
/// The gear one battleframe chassis ships with: the char-create loadout row it
/// was taken from and the modules slotted in it.
/// </summary>
public sealed class ChassisStockLoadout
{
    /// <summary>Chassis (battleframe) SDB id this loadout belongs to.</summary>
    public uint ChassisId { get; init; }

    /// <summary><c>dbcharacter::CharCreateLoadout</c> id the gear was read from.</summary>
    public uint LoadoutId { get; init; }

    /// <summary>
    /// The SDB row's own name, which names the tier the kit belongs to — e.g.
    /// <c>Accord Firecat - Player</c> or <c>Firecat Test Stage 2 Loadout</c>.
    /// </summary>
    public string Name { get; init; } = string.Empty;

    /// <summary>
    /// The frame's own name — the chassis item's localized name, e.g.
    /// <c>Firecat</c> — which is what the client calls it in the garage. The
    /// loadout row's <see cref="Name"/> names the tier it belongs to
    /// (<c>Firecat Test Stage 2 Loadout</c>), not something to show a player.
    /// </summary>
    public string DisplayName { get; init; } = string.Empty;

    /// <summary>Whether the SDB flags this as a starting loadout (the Accord frames).</summary>
    public bool IsStartingLoadout { get; init; }

    /// <summary>The modules the loadout slots, ordered by slot type.</summary>
    public IReadOnlyList<StockLoadoutSlot> Slots { get; init; } = [];
}

/// <summary>One slotted module of a <see cref="ChassisStockLoadout"/>.</summary>
public sealed class StockLoadoutSlot
{
    /// <summary>
    /// Loadout slot this module goes into, the SDB's <c>slot_type</c>: the same
    /// numbering as the GameServer's <c>LoadoutSlotType</c> (1 = primary weapon,
    /// 2 = secondary, 6 = HKM, 7..9 = abilities, 11 = backpack, 116/122..129 =
    /// chassis gear).
    /// </summary>
    public byte SlotType { get; init; }

    /// <summary>Item SDB id worn in the PvE configuration (0 when the slot is empty).</summary>
    public uint PveModule { get; init; }

    /// <summary>Item SDB id worn in the PvP configuration (0 when the slot is empty).</summary>
    public uint PvpModule { get; init; }
}
